pipeline {
    agent any

    tools {
        nodejs 'Node' 
    }


    environment {
        CHROME_BIN = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
        NODE_ENV = 'test'

    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SamyuktaNair/React_Jenkins_test.git'
            }
        }

        stage('Install Dependencies') {
             steps {
                dir('react-selenium-test') {
                    echo 'Installing Node dependencies...'
                    sh 'npm install'
                }
        }
        }

        stage('Build App') {
            steps {
                dir('react-selenium-test') {
                    echo 'Building React app...'
                    sh 'npm run build'
                }
            }
        }

        stage('Start Vite App') {
            steps {
                dir('react-selenium-test') {
                    echo 'Starting Vite development server...'
                    
                    sh 'nohup npm run dev &'
                    echo 'Waiting for the app to start...'
                    sleep 10
                }
            }
        }

        stage('Run Selenium Tests') {
            steps {
                dir('react-selenium-test/tests') {
                    echo 'Running Selenium tests...'
                    
                    sh 'npm test'
                }
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up background processes...'
                
                sh "pkill -f 'node' || true"
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete.'
        }
    }
}
